### ISSUE TITLE
How to debug litebsd kernel with gdb on qemu?

### ISSUE THREAD

**Issue by deyuhua** [sergev/LiteBSD#68]

**Comment by deyuhua** [comment]
@sergev I read book _TCP-IP illustrated_ with LiteBSD recently in qemu, but i don't know how to debug kernel, could you place write a document about this topic? thank you every much!

**Comment by elect-gombe** [comment]
I use `gdb-multiarch` for debugging.
```sh
$ qemu-system-mipsel -machine pic32mz-wifire\
     -nographic\
     -monitor none\
     -serial vc\
     -serial vc\
     -serial vc\
     -serial stdio\
     -bios boot-wifire.hex\
     -kernel ./sys/compile/WIFIRE.pic32/vmunix.hex\
     -sd sdcard.img\
     -S -gdb tcp::1234
```
```
$ gdb-multiarch <binary path>/vmunix.elf 

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/gombe/workspace/LiteBSD/sys/compile/WIFIRE.pic32/vmunix.elf...done.
(gdb) set arch mips
The target architecture is assumed to be mips
(gdb) set endian little
The target is assumed to be little endian
(gdb) tar ext:1234
Remote debugging using :1234
0x9d00197c in idle ()
(gdb) where
#0  0x9d00197c in idle ()
#1  0x9d00b074 in mi_switch () at ../../kern/kern_synch.c:600
#2  0xc0106800 in ?? ()
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x9d00197c in idle ()
(gdb) where
#0  0x9d00197c in idle ()
#1  0x9d00b074 in mi_switch () at ../../kern/kern_synch.c:600
warning: GDB can't find the start of the function at 0xc01067ff.

    GDB is unable to find the start of the function at 0xc01067ff
and thus can't determine the size of that function's stack frame.
This means that GDB may be unable to access that stack frame, or
the frames below it.
    This problem is most likely caused by an invalid program counter or
stack pointer.
    However, if you think GDB should simply search farther back
from 0xc01067ff for code which looks like the beginning of a
function, you can increase the range of the search using the `set
heuristic-fence-post' command.
#2  0xc0106800 in ?? ()
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x9d00197c in idle ()
(gdb) where
#0  0x9d00197c in idle ()
#1  0x9d00b074 in mi_switch () at ../../kern/kern_synch.c:600
warning: GDB can't find the start of the function at 0xc01067ff.
#2  0xc0106800 in ?? ()
(gdb) 
```
Reference:
[Cross debugging for ARM / MIPS ELF with QEMU/toolchain](https://grabduck.com/s/ahOcqPSg)

**Comment by deyuhua** [comment]
@elect-gombe thank for your reply
